# Generated by Django 5.2.4 on 2025-07-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.TextField(blank=True, null=True, verbose_name='Задача клиента (The Challenge)'),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.TextField(blank=True, null=True, verbose_name='Результат (The Outcome)'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True, verbose_name='URL-адрес (slug)'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, null=True, verbose_name='Наше решение (The Solution)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание (для карточки)'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись к изображению')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора отзыва')),
                ('author_position', models.CharField(max_length=100, verbose_name='Должность, компания')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='core.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
